services:
  postgres:
    image: postgres:15
    container_name: event_processor_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_processor
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrations:
    image: node:20-alpine
    container_name: event_processor_migrations
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/event_processor"
    command: >
      sh -c "npm install && npx prisma migrate deploy && npx prisma generate"

  nats:
    image: nats:latest
    container_name: event_processor_nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222",  "--store_dir", "/var/lib/nats/jetstream"]
    volumes:
      - nats-data:/var/lib/nats/jetstream 

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: event_processor_gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      NATS_URL: "nats://nats:4222"
      GATEWAY_PORT: 3000
    depends_on:
      - nats
  
  publisher:
    image: andriiuni/events
    container_name: events_publisher
    restart: always
    platform: linux/arm64/v8  # Explicitly set the platform
    network_mode: "host"  # Use host network - container shares network with host
    environment:
      EVENT_ENDPOINT: "http://192.168.0.106:3000/events"  # Use localhost since we're in host network mode
    depends_on:
      - nats
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  nats-data:
  postgres-data:
