services:
  postgres:
    image: postgres:15
    container_name: event_processor_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_processor
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrations:
    image: node:20
    container_name: event_processor_migrations
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/event_processor"
    command: >
      sh -c "npm install && npx prisma migrate deploy && npx prisma generate"

volumes:
  postgres-data:
