services:
  postgres:
    image: postgres:15
    container_name: event_processor_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_processor
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrations:
    image: node:20-alpine
    container_name: event_processor_migrations
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/event_processor"
    command: >
      sh -c "npm install && npx prisma migrate deploy && npx prisma generate"

  publisher:
    image: andriiuni/events
    container_name: events_publisher
    restart: always
    platform: linux/arm64/v8  # Explicitly set the platform
    environment:
      EVENT_ENDPOINT: "http://gateway:3000/events"
    depends_on:
      - nats
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nats:
    image: nats:latest
    container_name: event_processor_nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222",  "--store_dir", "/var/lib/nats/jetstream"]
    volumes:
      - nats-data:/var/lib/nats/jetstream
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"   
    
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: event_processor_gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      NATS_URL: "nats://nats:4222"
      GATEWAY_PORT: 3000
    depends_on:
      - nats
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"
    
  prometheus:
    image: prom/prometheus:latest
    container_name: event_processor_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - gateway
      # - fs-collector
      # - ttk-collector

  # fs-collector:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.fscollector
  #   container_name: event_processor_fscollector
  #   restart: always
  #   environment:
  #     NATS_URL: "nats://nats:4222"
  #   depends_on:
  #     - nats

  # ttk-collector:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ttkcollector
  #   container_name: event_processor_ttkcollector
  #   restart: always
  #   environment:
  #     NATS_URL: "nats://nats:4222"
  #   depends_on:
  #     - nats

  # reporter:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.reporter
  #   container_name: event_processor_reporter
  #   restart: always
  #   environment:
  #     NATS_URL: "nats://nats:4222"
  #     DATABASE_URL: "postgresql://user:password@postgres:5432/event_processor"
  #   depends_on:
  #     - nats
  #     - postgres
  
volumes:
  nats-data:
  postgres-data:
